font=UbuntuMonoNerdFontMono-Regular:size=10
dpi-aware=yes

[colors-dark]
alpha=0.55
background=0a2c47
foreground=eaf6fc

# black
regular0 = 143852
bright0  = 2d5266

# red
regular1 = ff7e6b
bright1  = ff9f8f

# green
regular2 = 6fd88a
bright2  = 9df0ae

# yellow
regular3 = ffc857
bright3  = ffdb8c

# blue
regular4 = 5aa8e0
bright4  = 8fd4ff

# magenta
regular5 = d68ee8
bright5  = e8b3f2

# cyan
regular6 = 3fd8d0
bright6  = 7fefe6

# white
regular7 = c9e4ee
bright7  = eaf6fc
